config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations" }
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  # GET /comments or /comments.json
  def index
    @comments = Comment.all.order("created_at DESC")
  end

  # GET /comments/1 or /comments/1.json
  def show
    @comment = @post.comments.build(comment_params)
  end

  # GET /comments/new
  def new
    @comment = @post.comments.build(comment_params)
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
  end

  # POST /comments or /comments.json
  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to root_path, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to root_path, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:post_id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.buil
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to root_path, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:post)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_udpate_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @comment]) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :content,
        input_html: {class: "textarea"},
        wrapper: false,
        autofocus: true,
        label: false
      %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/comments/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Comment</h1>
				<%= render 'form', comment: @comment %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', root_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.post_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForeverApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar is-info">
      <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-5">Forever Sample App</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="accountNavbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
      </div>
      <div id="accountNavbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <% if user_signed_in? %>
                <p class="control">
                  <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
                </p>
                <p class="control">
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "button is-info is-inverted" %>
                </p>
              <% else %>
                <p class="control">
                  <%= link_to "Sign Up", new_user_registration_path, class: "button is-info is-inverted" %>
                </p>
                <p class="control">
                  <%= link_to "Sign In", new_user_session_path, class: "button is-info is-inverted" %>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :post, 
        label: "Post Something New",
        input_html: {class: "textarea"},
        wrapper: false,
        label_html: {class: "label"},
        placeholder: "Write your message here...",
        autofocus: true 
      %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info" %>
  <% end %>

app/views/posts/_posts.html.erb
<div class="column is-three-quarters">
  <% if user_signed_in? %>
    <article class="media box">
      <figure class="media-left">
        <p class="image is-64x">
          <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
        </p>
      </figure>
      <div class="media-content">
        <%= render "posts/form" %>
      </div>
    </article>
  <% end %>

  <% @posts.each do | post | %>
    <div class="column">
      <article class="media box">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(post.user.email, size: 64, alt: post.user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div id="post">
            <div class="content">
              <strong id="post-author"><%= post.user.name %></strong>
              <p class="post-text"><%= post.post %></p>
            </div>
            <nav id="post-buttons" class="level">
              <div class="level-left is-mobile">
                <% if post.user == current_user %>
                  <%= link_to edit_post_path(post), class: "level-item" do %>
                    <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                  <% end %>
                  <%= link_to post, method: :delete, data: { confirm: "Are you sure you want to delete this post?"} do %>
                    <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                  <% end %>
                <% end %>
              </div>
            </nav>
          </div>
          <% if post.comments %>
            <div class="post-bottom">
              <% post.comments.each do |comment| %>
                <div id="comment">
                  <div class="user-name">
                    <%= comment.user.name %>
                  </div>
                  <div class="comment_content">
                    <%= comment.content %>
                  </div>
                  <% if comment.user == current_user %>
                    <%= link_to edit_post_comment_path(post, comment) do %>
                      <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                    <% end %>
                  <% end %>
                  <% if comment.user == current_user || comment.post.user == current_user %>
                    <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Delete comment?" } do %>
                      <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            </div>
            <% if user_signed_in? %>
              <%= form_for [post, post.comments.new] do |f| %>
                <%= f.text_field :content, placeholder: "Leave a comment...", class: "comment-form" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Post</h1>
				<%= render 'form', post: @post %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', root_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/posts/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render "posts" %>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post.post %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>